// ============================================================================
// sound category types for classification results
// this file defines all typescript interfaces and types used throughout
// the application for sound detection and notification tracking
// ============================================================================

// ============================================================================
// sound category enum type
// sounds are classified into three main categories:
// - alarming: urgent sounds requiring immediate attention (fire alarm, siren)
// - background: ambient environmental noise (traffic, hvac, typing)
// - safe: normal non-urgent sounds (speech, music, silence)
// ============================================================================
export type SoundCategory = 'alarming' | 'background' | 'safe';

// ============================================================================
// detected sound interface
// represents a single sound detection event from the ml model
// contains the classification result and metadata
// ============================================================================
export interface DetectedSound {
  // the class name from the teachable machine model (e.g., "fire alarm")
  label: string;
  // the category we mapped this sound to (alarming, background, or safe)
  category: SoundCategory;
  // how confident the model is in this prediction (0.0 to 1.0)
  confidence: number;
  // when this sound was detected (javascript date object)
  timestamp: Date;
}

// ============================================================================
// notification record interface
// represents a sound detection that was saved to the database
// includes database-specific fields like id and timestamps
// ============================================================================
export interface NotificationRecord {
  // unique identifier generated by the database (uuid)
  id: string;
  // the user who received this notification (links to auth.users)
  user_id: string;
  // the detected sound class name from the model
  sound_label: string;
  // which category this sound belongs to
  category: SoundCategory;
  // the model's confidence level (0.0 to 1.0)
  confidence: number;
  // iso timestamp when the sound was detected
  detected_at: string;
}

// ============================================================================
// user settings interface
// stores the user's accessibility and preference settings
// these are persisted in the database and loaded on login
// ============================================================================
export interface UserSettings {
  // unique identifier for this settings record
  id: string;
  // the user these settings belong to
  user_id: string;
  // text size multiplier (0.8 = 80%, 1.0 = 100%, 1.6 = 160%)
  text_size: number;
  // button/control size multiplier for easier tapping
  button_size: number;
  // icon size multiplier for visibility
  icon_size: number;
  // color theme: dark (high contrast), light, or light-contrast
  theme: 'dark' | 'light' | 'light-contrast';
  // whether haptic feedback (vibration) is enabled
  haptic_enabled: boolean;
}

// ============================================================================
// teachable machine prediction interface
// raw prediction result from the tensorflow model
// one of these is returned for each class the model was trained on
// ============================================================================
export interface TmPrediction {
  // the class name (sound label) this prediction is for
  className: string;
  // probability that the input matches this class (0.0 to 1.0)
  probability: number;
}

// ============================================================================
// sound category mapping
// maps specific sound labels from the teachable machine model
// to our three main categories (alarming, background, safe)
// this allows the app to know how to respond to each sound type
// ============================================================================
export const soundCategoryMap: Record<string, SoundCategory> = {
  // ========== alarming sounds ==========
  // these require immediate user attention and trigger strong haptics
  'fire alarm': 'alarming',
  'smoke alarm': 'alarming',
  'siren': 'alarming',
  'car horn': 'alarming',
  'glass breaking': 'alarming',
  'scream': 'alarming',
  'dog bark': 'alarming',
  'baby cry': 'alarming',
  'door knock': 'alarming',
  'doorbell': 'alarming',
  'alarm': 'alarming',
  'horn': 'alarming',
  'emergency': 'alarming',
  
  // ========== background noise ==========
  // ambient environmental sounds that are informational only
  'background noise': 'background',
  'traffic': 'background',
  'wind': 'background',
  'rain': 'background',
  'crowd': 'background',
  'typing': 'background',
  'hvac': 'background',
  'noise': 'background',
  'ambient': 'background',
  '_background noise_': 'background',
  
  // ========== safe sounds ==========
  // normal sounds that don't require attention
  'silence': 'safe',
  'speech': 'safe',
  'music': 'safe',
  'birds': 'safe',
  'water': 'safe',
  'talking': 'safe',
  'voice': 'safe',
  '_silence_': 'safe',
};

// ============================================================================
// helper function to categorize a sound label
// takes a raw label from the teachable machine model and returns
// the appropriate category (defaults to 'background' if unknown)
// ============================================================================
export function categorizeSound(label: string): SoundCategory {
  // normalize the label to lowercase and trim whitespace
  // this handles variations like "Fire Alarm" vs "fire alarm"
  const normalizedLabel = label.toLowerCase().trim();
  
  // look up in our mapping, default to 'background' if not found
  // unknown sounds are treated as background noise for safety
  return soundCategoryMap[normalizedLabel] || 'background';
}
